### ISSUE TITLE
Unhandled exception. EventStore.ClientAPI.Exceptions.ConnectionClosedException

### ISSUE THREAD

**Issue by AndiRudi** [AndiRudi/EventSourcedBookingSample#1]
First do `docker-compose up` to start EventStoreDb
Then do `dotnet run` to run the application
It connects but then fails with error
 
```
Unhandled exception. EventStore.ClientAPI.Exceptions.ConnectionClosedException: Connection 'ES-4be5efb6-4fa1-4a57-af16-32bd2402e690' was closed.
   at EventStore.ClientAPI.Internal.EventStoreNodeConnection.AppendToStreamAsync(String stream, Int64 expectedVersion, IEnumerable`1 events, UserCredentials userCredentials)
   at EventSourcedBookingSample.Program.Main(String[] args) in /Users/andi/repos/EventSourcedBookingSample/Program.cs:line 37
   at EventSourcedBookingSample.Program.<Main>(String[] args)
```

**Comment by AndiRudi** [comment]
It seems that there is a new client package for .net called `EventStore.Client.Grpc.Streams` which should be used instead so I close this
